### ISSUE TITLE
Hardware configuration for AllenNLP Coref + ELMo

### ISSUE THREAD

**Issue by feralvam** [ljinstat/coreference_resolution#1]
Hi!
Thank you for the configuration file for running the AllenNLP coreference model with ELMo. I was wondering about the hardware configuration you used to run it, because I run out of GPU memory when I try it.

Best,
Fernando

**Comment by ljinstat** [comment]
Hello!

My GPU is Tesla P100 with 16GB RAM. The same as you, I encountered the out of memory issue when setting max_antecedents as 100. So I tried to reduce it. For now, max_antecedents = 75 is the maximum value that I can run the model with successfully. You can reduce further this value as I did, otherwise you could modify other parameters that matters at the step of pruning.  

By the way, are you doing some recherches about coreference? I am curious about what others are doing about it. Have you discovered any interesting results?

Cheers,
Ling

**Comment by feralvam** [comment]
Hi!
Thanks for the quick reply.  I am familiarizing myself with the allennlp models and how to use ELMo. I'm not doing research on Coreference Resolution at the moment.
